FROM node:20 AS builder
SHELL ["/bin/bash", "-c"]

WORKDIR /app

RUN npm install -g nx

COPY [ "package.json", "yarn.lock", "./" ]

RUN yarn --frozen-lockfile

COPY . .

# RUN yarn test

RUN nx run-many -t build -p ai aibackend --parallel=$(grep -c ^processor /proc/cpuinfo) && \
    .devops/set-build-props.sh -p=ai

RUN yarn --cwd dist/apps/ai/backend --frozen-lockfile

FROM node:20-slim AS runner
WORKDIR /app
SHELL ["/bin/bash", "-c"]

ENV FRONTEND_PROJECT=ai

# # We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# # Install necessary libraries for Puppeteer
RUN apt-get update && apt-get install -y \
    gnupg \
    wget \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    chromium \
    --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/dist ./dist

RUN mkdir -p dist/apps/ai/device-processed && chown -R node:node dist/apps/ai/device-processed

USER node

ENTRYPOINT node /app/dist/apps/ai/backend/main.js